[workspace]
members = [
    "chordflow_desktop",
    "chordflow_music_theory",
]

[workspace.package]
version = "0.6.1"

[workspace.metadata.release]
shared-version = true
publish = false
push = false
tag-name = "v{{version}}"
pre-release-commit-message = "chore: release v{{version}}"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"


[bundle]
resources = ["assets/*"]
