name: Build

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ "main" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          #          - build: linux
          #            os: ubuntu-latest
          #            target: x86_64-unknown-linux-musl
          #            dependencies: |
          #              sudo apt-get update && sudo apt-get install -y --reinstall libasound2-dev pkg-config
          #              echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            dependencies: |
              brew install cmake portaudio pkg-config

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-msvc
            dependencies: |
              choco install vcpkg -y
              vcpkg install portaudio:x64-windows

    steps: 
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: ${{ matrix.dependencies }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets: ${{ matrix.target }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        
  tui:
    needs: test
    name: TUI
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            dependencies: |
              brew install cmake portaudio pkg-config

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-msvc
            dependencies: |
              choco install vcpkg -y
              vcpkg install portaudio:x64-windows

    steps: 
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: ${{ matrix.dependencies }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets: ${{ matrix.target }}
        
    - name: Change directory
      shell: bash
      run: |
        cd chordflow_tui
        
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}
        

    - name: Build Archive
      shell: bash
      run: |
        cd ..
        binary_name="chordflow_tui"

        dirname="${binary_name}-${{ env.VERSION }}-${{ matrix.target }}"
        mkdir ${dirname}

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          mv target/${{ matrix.target }}/release/${binary_name}.exe ${dirname}
        else
          mv target/${{ matrix.target }}/release/${binary_name} ${dirname}
        fi
        
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          7z a "${dirname}.zip" ${dirname}
          echo "ASSET=${dirname}.zip" >> ${GITHUB_ENV}
        else
          tar -czf "${dirname}.tar.gz" ${dirname}
          echo "ASSET=${dirname}.tar.gz" >> ${GITHUB_ENV}
        fi

  desktop:
    name: Desktop-MacOS
    runs-on: macos-latest
    needs: test  

    steps: 
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install cmake portaudio pkg-config

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets:  x86_64-apple-darwin

    - name: Install Dioxus-CLI
      shell: bash
      run: cargo install dioxus-cli

    - name: Build Archive
      shell: bash
      run: |
        cd chordflow-desktop
        dx bundle --release
        
        
        app_name="ChordFlowDesktop.app"
        dmg_name="ChordFlowDesktop_${{ env.VERSION }}_aarch64.dmg"
        
        mv ../target/dx/chordflow-desktop/bundle/macos/bundle/macos/${app_name} ${app_name}
        mv ../target/dx/chordflow-desktop/bundle/macos/bundle/dmg/${dmg_name} ${dmg_name}
        
        echo "APP=${app_name}" >> ${GITHUB_ENV}
        echo "DMG=${dmg_name}" >> ${GITHUB_ENV}