name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          #          - build: linux
          #            os: ubuntu-latest
          #            target: x86_64-unknown-linux-musl
          #            dependencies: |
          #              sudo apt-get update && sudo apt-get install -y --reinstall libasound2-dev pkg-config
          #              echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            dependencies: |
              brew install cmake portaudio pkg-config

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-msvc
            dependencies: |
              choco install vcpkg -y
              vcpkg install portaudio:x64-windows

    steps: 
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: ${{ matrix.dependencies }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets: ${{ matrix.target }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}

    - name: Build Archive
      shell: bash
      run: |
        binary_name="chordflow_tui"

        dirname="${binary_name}-${{ env.VERSION }}-${{ matrix.target }}"
        mkdir ${dirname}

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          mv target/${{ matrix.target }}/release/${binary_name}.exe ${dirname}
        else
          mv target/${{ matrix.target }}/release/${binary_name} ${dirname}
        fi
        
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          7z a "${dirname}.zip" ${dirname}
          echo "ASSET=${dirname}.zip" >> ${GITHUB_ENV}
        else
          tar -czf "${dirname}.tar.gz" ${dirname}
          echo "ASSET=${dirname}.tar.gz" >> ${GITHUB_ENV}
        fi

      

