name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps: 
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install cmake portaudio pkg-config

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        
  tui:
    needs: test
    name: TUI
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include: 
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: macos-latest
          target: aarch64-apple-darwin

    steps: 
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install cmake portaudio pkg-config

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets: ${{ matrix.target }}
        
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}
        

    - name: Build Archive
      shell: bash
      run: |
        mkdir artifacts
        binary_name="chordflow_tui"
        current_version=$(cargo pkgid | cut -d "#" -f2)
        app_name="${binary_name}-${current_version}-${{ matrix.target }}"
        tar -czf artifacts/${app_name}.tar.gz target/${{ matrix.target }}/release/${binary_name} 

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-tui-${{ matrix.target }}
        path: artifacts/

  desktop:
    name: Desktop-MacOS
    needs: test  
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include: 
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: macos-latest
          target: aarch64-apple-darwin

    steps: 
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install cmake portaudio pkg-config

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with: 
        targets: ${{ matrix.target }}

    - name: Install Dioxus-CLI
      shell: bash
      run: cargo install dioxus-cli

    - name: Build Archive
      shell: bash
      working-directory: ./chordflow_desktop
      run: |
        mkdir ../artifacts
        dx bundle --release
        current_version=$(cargo pkgid | cut -d "#" -f2)
        dmg_name="ChordFlow-${current_version}-${{ matrix.target }}.dmg"
        mv ../target/dx/chordflow_desktop/bundle/macos/bundle/dmg/ChordflowDesktop_*.dmg ../artifacts/${dmg_name}

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-desktop-macos-${{ matrix.target }}
        path: artifacts/

        
  release:
    needs: [desktop, tui]
    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:
      - name: Get Version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download macOS Intel TUI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-tui-x86_64-apple-darwin
          path: artifacts/

      - name: Download macOS Arch TUI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-tui-aarch64-apple-darwin
          path: artifacts/

      - name: Download macOS Intel Desktop Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-desktop-macos-x86_64-apple-darwin
          path: artifacts/

      - name: Download macOS Arch Desktop Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-desktop-macos-aarch64-apple-darwin
          path: artifacts/

      - name: Show artifacts
        shell: bash
        run: ls -la artifacts

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/chordflow_tui-${{ env.VERSION }}-x86_64-apple-darwin.tar.gz
            artifacts/chordflow_tui-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz
            artifacts/ChordFlow-${{ env.VERSION }}-x86_64-apple-darwin.dmg
            artifacts/ChordFlow-${{ env.VERSION }}-aarch64-apple-darwin.dmg
