[package]
name = "chordflow_music_theory"
version = "0.3.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
itertools = "0.14.0"
rand = "0.9.0"
strum = { version = "0.27.0", features = ["derive"] }
strum_macros = "0.27.0"
